### ISSUE TITLE
Add security headers

### ISSUE THREAD

**Issue by freaktechnik** [mozillach/mozilla.ch-docker#5]
The apache config this container currently uses doesn't add any security headers.
We should at least add `X-Frame-Options`, `X-Content-Type-Options` and `X-XSS-Protection`. CSP would be great, too, though probably still pretty broad thanks to the twitter widget and mozillians avatars.

**Comment by J0WI** [comment]
At least X-Frame-Options is obsolete with CSP 2.0.
We should also use (preloaded) HSTS and may be HPKP. But this depends on https://github.com/mozillach/mozilla.ch/issues/17

**Comment by freaktechnik** [comment]
Well yes, but luckily all browsers fully support CSP 2.0, right... And yes, HSTS is great if we add TLS to the container, but that'll require some other changes...

**Comment by freaktechnik** [comment]
The HTTPS enabled container sends the HSTS by default.

**Comment by freaktechnik** [comment]
Implemented in mozillach/mozilla.ch

**Comment by J0WI** [comment]
The Mozillians faces are using inline styles.
I would also like to see `referrer 'origin-when-cross-origin';` and `plugin-types 'none';` :)
I can add them myself if you agree.

**Comment by MichaelKohler** [comment]
That makes sense, I'd say go ahead :)

**Comment by freaktechnik** [comment]
oh, I didn't test with a mozillians API key, since I didn't teach that to the docker container running script yet. Adding 'unsafe-inline' for CSS shouldn't be too much of a worry though, it's the JS unsafe-inline that gives me shivers...

**Comment by J0WI** [comment]
@freaktechnik thx for https://github.com/mozillach/mozilla.ch/commit/c356621c3e258c9bd3b2884055e2ee15644720bc
I just saw, that the header is only added on .php files. This is not a good practice, since there are some other file extensions that mater (html, svg, php5, asp, aspx, svgz ...). I'm even not sure if Apache handles them case sensitive. I tend to apply the header on all requests. If we have HTTP/2 this shouldn't be a performance issue.

**Comment by freaktechnik** [comment]
The reason I'm not adding it on svg is because it breaks our svgs. We need a different CSP for them, but I don't know how firefox allows inline styles for SVGs.
